#**스마트폰 센서 데이터 기반 모션 분류**
# 단계3 : 단계별 모델링


## 0.미션

단계별로 나눠서 모델링을 수행하고자 합니다.  

* 단계1 : 정적(0), 동적(1) 행동 분류 모델 생성
* 단계2 : 세부 동작에 대한 분류모델 생성
    * 단계1 모델에서 0으로 예측 -> 정적 행동 3가지 분류 모델링
    * 단계1 모델에서 1으로 예측 -> 동적 행동 3가지 분류 모델링
* 모델 통합
    * 두 단계 모델을 통합하고, 새로운 데이터에 대해서 최종 예측결과와 성능평가가 나오도록 함수로 만들기
* 성능 비교
    * 기본 모델링의 성능과 비교
    * 모든 모델링은 [다양한 알고리즘 + 성능 튜닝]을 수행해야 합니다.
    * 성능 가이드
            * Accuracy : 0.980~1.00


## 1.환경설정

* 세부 요구사항
    - 경로 설정 : 다음의 두가지 방법 중 하나를 선택하여 폴더를 준비하고 데이터를 로딩하시오.
        * 1) 로컬 수행(Ananconda)
            * 제공된 압축파일을 다운받아 압축을 풀고
            * anaconda의 root directory(보통 C:/Users/< ID > 에 project 폴더를 만들고, 복사해 넣습니다.
        * 2) 구글콜랩
            * 구글 드라이브 바로 밑에 project 폴더를 만들고,
            * 데이터 파일을 복사해 넣습니다.
    
    - 기본적으로 필요한 라이브러리를 import 하도록 코드가 작성되어 있습니다.
        * 필요하다고 판단되는 라이브러리를 추가하세요.


### (1) 경로 설정

#### 1) 로컬 수행(Anaconda)
* project 폴더에 필요한 파일들을 넣고, 본 파일을 열었다면, 별도 경로 지정이 필요하지 않습니다.

In [161]:
# path = 'C:/Users/User/Desktop/'

#### 2) 구글 콜랩 수행

* 구글 드라이브 연결

In [162]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [163]:
# path = '/content/drive/MyDrive/project/'

### (2) 라이브러리 불러오기

#### 1) 라이브러리 로딩

In [164]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 필요하다고 판단되는 라이브러리를 추가하세요.

#### 2) 제공 함수 생성
* 변수 중요도를 시각화할 수 있는 함수를 제공합니다.
* 입력 :
    * importance : 트리모델의 변수 중요도(예: model.feature_importances_)
    * names : 변수 이름 목록(예 : x_train.columns
    * result_only  : 변수 중요도 순으로 데이터프레임만 return할지, 그래프도 포함할지 결정. False이면 결과 데이터프레임 + 그래프
    * topn : 중요도 상위 n개만 표시. all 이면 전체.
* 출력 :
    * 중요도 그래프 : 중요도 내림차순으로 정렬
    * 중요도 데이터프레임 : 중요도 내림차순으로 정렬

In [165]:
# 변수의 특성 중요도 계산하기
def plot_feature_importance(importance, names, result_only = False, topn = 'all'):
    feature_importance = np.array(importance)
    feature_name = np.array(names)

    data={'feature_name':feature_name,'feature_importance':feature_importance}
    fi_temp = pd.DataFrame(data)

    #변수의 특성 중요도 순으로 정렬하기
    fi_temp.sort_values(by=['feature_importance'], ascending=False,inplace=True)
    fi_temp.reset_index(drop=True, inplace = True)

    if topn == 'all' :
        fi_df = fi_temp.copy()
    else :
        fi_df = fi_temp.iloc[:topn]

    #변수의 특성 중요도 그래프로 그리기
    if result_only == False :
        plt.figure(figsize=(10,20))
        sns.barplot(x='feature_importance', y='feature_name', data = fi_df)

        plt.xlabel('importance')
        plt.ylabel('feature name')
        plt.grid()

    return fi_df

### (3) 데이터 불러오기

* 주어진 데이터셋
    * data01_train.csv : 학습 및 검증용
    * data01_test.csv : 테스트용
    * feature.csv : feature 이름을 계층구조로 정리한 데이터

* 세부 요구사항
    * 칼럼 삭제 : data01_train.csv와 data01_test.csv 에서 'subject' 칼럼은 불필요하므로 삭제합니다.

#### 1) 데이터로딩

In [166]:
data = pd.read_csv('/content/drive/MyDrive/KT_미니프로젝트_4/data01_train.csv')
test = pd.read_csv('/content/drive/MyDrive/KT_미니프로젝트_4/data01_test.csv')
features = pd.read_csv('/content/drive/MyDrive/KT_미니프로젝트_4/features.csv')

In [167]:
# 불필요한 칼럼 삭제
data.drop('subject', axis=1, inplace=True)
test.drop('subject', axis=1, inplace=True)

#### 2) 기본 정보 조회

In [168]:
#전체 데이터의 행,열 개수 확인
data.shape

(5881, 562)

In [169]:
#전체 데이터의 상위 5개 행 확인
data.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288508          -0.009196          -0.103362         -0.988986   
1           0.265757          -0.016576          -0.098163         -0.989551   
2           0.278709          -0.014511          -0.108717         -0.997720   
3           0.289795          -0.035536          -0.150354         -0.231727   
4           0.394807           0.034098           0.091229          0.088489   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.962797         -0.967422         -0.989000         -0.962596   
1         -0.994636         -0.987435         -0.990189         -0.993870   
2         -0.981088         -0.994008         -0.997934         -0.982187   
3         -0.006412         -0.338117         -0.273557          0.014245   
4         -0.106636         -0.388502         -0.010469         -0.109680   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-skewness()  \
0         -0.965650         -0.929747  ...                        -0.487737   
1         -0.987558         -0.937337  ...                        -0.237820   
2         -0.995017         -0.942584  ...                        -0.535287   
3         -0.347916          0.008288  ...                        -0.004012   
4         -0.346372          0.584131  ...                        -0.157832   

   fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                        -0.816696                    -0.042494   
1                        -0.693515                    -0.062899   
2                        -0.829311                     0.000265   
3                        -0.408956                    -0.255125   
4                        -0.563437                    -0.044344   

   angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
0                             -0.044218                          0.307873   
1                              0.388459                         -0.765014   
2                             -0.525022                         -0.891875   
3                              0.612804                          0.747381   
4                             -0.845268                         -0.974650   

   angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
0                              0.072790             -0.601120   
1                              0.771524              0.345205   
2                              0.021528             -0.833564   
3                             -0.072944             -0.695819   
4                             -0.887846             -0.705029   

   angle(Y,gravityMean)  angle(Z,gravityMean)            Activity  
0              0.331298              0.165163            STANDING  
1             -0.769186             -0.147944              LAYING  
2              0.202434             -0.032755            STANDING  
3              0.287154              0.111388             WALKING  
4              0.264952              0.137758  WALKING_DOWNSTAIRS  

[5 rows x 562 columns]

In [170]:
#전체 데이터의 수치형 변수 분포 확인
data.describe()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
count        5881.000000        5881.000000        5881.000000   
mean            0.274811          -0.017799          -0.109396   
std             0.067614           0.039422           0.058373   
min            -0.503823          -0.684893          -1.000000   
25%             0.262919          -0.024877          -0.121051   
50%             0.277154          -0.017221          -0.108781   
75%             0.288526          -0.010920          -0.098163   
max             1.000000           1.000000           1.000000   

       tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
count       5881.000000       5881.000000       5881.000000       5881.000000   
mean          -0.603138         -0.509815         -0.604058         -0.628151   
std            0.448807          0.501815          0.417319          0.424345   
min           -1.000000         -0.999844         -0.999667         -1.000000   
25%           -0.992774         -0.977680         -0.980127         -0.993602   
50%           -0.943933         -0.844575         -0.856352         -0.948501   
75%           -0.242130         -0.034499         -0.262690         -0.291138   
max            1.000000          0.916238          1.000000          1.000000   

       tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
count       5881.000000       5881.000000       5881.000000  ...   
mean          -0.525944         -0.605374         -0.465490  ...   
std            0.485115          0.413043          0.544995  ...   
min           -0.999419         -1.000000         -1.000000  ...   
25%           -0.977865         -0.980112         -0.936067  ...   
50%           -0.849266         -0.849896         -0.878729  ...   
75%           -0.068857         -0.268539         -0.013690  ...   
max            0.967664          1.000000          1.000000  ...   

       fBodyBodyGyroJerkMag-meanFreq()  fBodyBodyGyroJerkMag-skewness()  \
count                      5881.000000                      5881.000000   
mean                          0.126955                        -0.305883   
std                           0.249176                         0.322808   
min                          -0.965725                        -0.979261   
25%                          -0.021610                        -0.541969   
50%                           0.133887                        -0.342923   
75%                           0.288944                        -0.127371   
max                           0.946700                         0.989538   

       fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
count                      5881.000000                  5881.000000   
mean                         -0.623548                     0.008524   
std                           0.310371                     0.339730   
min                          -0.999765                    -0.976580   
25%                          -0.845985                    -0.122361   
50%                          -0.712677                     0.010278   
75%                          -0.501158                     0.154985   
max                           0.956845                     1.000000   

       angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
count                           5881.000000                       5881.000000   
mean                              -0.001185                          0.009340   
std                                0.447197                          0.608190   
min                               -1.000000                         -1.000000   
25%                               -0.294369                         -0.481718   
50%                                0.005146                          0.011448   
75%                                0.285030                          0.499857   
max                                1.000000                          0.998702   

       angle(tBodyGyroJ

In [171]:
#전체 데이터의 모든 변수 확인
data.columns

Index(['tBodyAcc-mean()-X', 'tBodyAcc-mean()-Y', 'tBodyAcc-mean()-Z',
       'tBodyAcc-std()-X', 'tBodyAcc-std()-Y', 'tBodyAcc-std()-Z',
       'tBodyAcc-mad()-X', 'tBodyAcc-mad()-Y', 'tBodyAcc-mad()-Z',
       'tBodyAcc-max()-X',
       ...
       'fBodyBodyGyroJerkMag-skewness()', 'fBodyBodyGyroJerkMag-kurtosis()',
       'angle(tBodyAccMean,gravity)', 'angle(tBodyAccJerkMean),gravityMean)',
       'angle(tBodyGyroMean,gravityMean)',
       'angle(tBodyGyroJerkMean,gravityMean)', 'angle(X,gravityMean)',
       'angle(Y,gravityMean)', 'angle(Z,gravityMean)', 'Activity'],
      dtype='object', length=562)

## 2.데이터 전처리

* 세부 요구사항
    - Label 추가 : data 에 Activity_dynamic 를 추가합니다. Activity_dynamic은 과제1에서 is_dynamic과 동일한 값입니다.
    - x와 y1, y2로 분할하시오.
        * y1 : Activity
        * y2 : Activity_dynamic
    - train : val = 8 : 2 혹은 7 : 3
    - random_state 옵션을 사용하여 다른 모델과 비교를 위해 성능이 재현되도록 합니다.

In [172]:
# 'Activity'를 'Activity_dynamic' 변수로 변경
data['Activity_dynamic'] = data['Activity'].map({'STANDING': 0, 'SITTING': 0, 'LAYING': 0,
                                                           'WALKING': 1, 'WALKING_UPSTAIRS': 1, 'WALKING_DOWNSTAIRS': 1})
data.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288508          -0.009196          -0.103362         -0.988986   
1           0.265757          -0.016576          -0.098163         -0.989551   
2           0.278709          -0.014511          -0.108717         -0.997720   
3           0.289795          -0.035536          -0.150354         -0.231727   
4           0.394807           0.034098           0.091229          0.088489   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.962797         -0.967422         -0.989000         -0.962596   
1         -0.994636         -0.987435         -0.990189         -0.993870   
2         -0.981088         -0.994008         -0.997934         -0.982187   
3         -0.006412         -0.338117         -0.273557          0.014245   
4         -0.106636         -0.388502         -0.010469         -0.109680   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.965650         -0.929747  ...                        -0.816696   
1         -0.987558         -0.937337  ...                        -0.693515   
2         -0.995017         -0.942584  ...                        -0.829311   
3         -0.347916          0.008288  ...                        -0.408956   
4         -0.346372          0.584131  ...                        -0.563437   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.042494                             -0.044218   
1                    -0.062899                              0.388459   
2                     0.000265                             -0.525022   
3                    -0.255125                              0.612804   
4                    -0.044344                             -0.845268   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                          0.307873                              0.072790   
1                         -0.765014                              0.771524   
2                         -0.891875                              0.021528   
3                          0.747381                             -0.072944   
4                         -0.974650                             -0.887846   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  \
0             -0.601120              0.331298              0.165163   
1              0.345205             -0.769186             -0.147944   
2             -0.833564              0.202434             -0.032755   
3             -0.695819              0.287154              0.111388   
4             -0.705029              0.264952              0.137758   

             Activity  Activity_dynamic  
0            STANDING                 0  
1              LAYING                 0  
2            STANDING                 0  
3             WALKING                 1  
4  WALKING_DOWNSTAIRS                 1  

[5 rows x 563 columns]

In [173]:
target = ['Activity','Activity_dynamic']
x = data.drop(target, axis=1)
y1 = data['Activity']
y2 = data['Activity_dynamic']

In [174]:
from sklearn.model_selection import train_test_split
x_train, x_val, y2_train, y2_val = train_test_split(x, y2, test_size=0.3, random_state=1)

## **3.단계별 모델링**

![](https://github.com/DA4BAM/image/blob/main/step%20by%20step.png?raw=true)

### (1) 단계1 : 정적/동적 행동 분류 모델

* 세부 요구사항
    * 정적 행동(Laying, Sitting, Standing)과 동적 행동(Walking, Walking-Up, Walking-Down)을 구분하는 모델 생성.
    * 몇가지 모델을 만들고 가장 성능이 좋은 모델을 선정하시오.

#### 1) Logistic Regression

In [175]:
from sklearn.linear_model import LogisticRegression
model_lr = LogisticRegression()
model_lr.fit(x,y2)

y_pred_lr = model_lr.predict(x_val)

In [176]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print('accuracy :',accuracy_score(y2_val, y_pred_lr))
print('='*60)
print(confusion_matrix(y2_val, y_pred_lr))
print('='*60)
print(classification_report(y2_val, y_pred_lr))

accuracy : 1.0
[[954   0]
 [  0 811]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       954
           1       1.00      1.00      1.00       811

    accuracy                           1.00      1765
   macro avg       1.00      1.00      1.00      1765
weighted avg       1.00      1.00      1.00      1765



#### 2) RandomForest

In [177]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier()
model_rf.fit(x, y2)

y_pred_rf = model_rf.predict(x_val)

In [178]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print('accuracy :',accuracy_score(y2_val, y_pred_lr))
print('='*60)
print(confusion_matrix(y2_val, y_pred_lr))
print('='*60)
print(classification_report(y2_val, y_pred_lr))

accuracy : 1.0
[[954   0]
 [  0 811]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       954
           1       1.00      1.00      1.00       811

    accuracy                           1.00      1765
   macro avg       1.00      1.00      1.00      1765
weighted avg       1.00      1.00      1.00      1765



### (2) 단계2-1 : 정적 동작 세부 분류

* 세부 요구사항
    * 정적 행동(Laying, Sitting, Standing)인 데이터 추출
    * Laying, Sitting, Standing 를 분류하는 모델을 생성
    * 몇가지 모델을 만들고 가장 성능이 좋은 모델을 선정하시오.

In [179]:
# 정적 행동(Laying, Sitting, Standing)에 해당하는 데이터 추출
static_beh = data.loc[(data['Activity'] == 'LAYING')|(data['Activity'] == 'SITTING')|(data['Activity'] == 'STANDING')]

# 추출된 데이터 확인
display(static_beh)

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.288508          -0.009196          -0.103362   
1              0.265757          -0.016576          -0.098163   
2              0.278709          -0.014511          -0.108717   
7              0.272026          -0.001329          -0.125491   
8              0.284338           0.021956          -0.006925   
...                 ...                ...                ...   
5874           0.257476          -0.413865           0.017374   
5875           0.277378          -0.013298          -0.104322   
5876           0.277194          -0.012389          -0.131974   
5878           0.267981          -0.018348          -0.107440   
5880           0.283815          -0.040658          -0.138018   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
0            -0.988986         -0.962797         -0.967422         -0.989000   
1            -0.989551         -0.994636         -0.987435         -0.990189   
2            -0.997720         -0.981088         -0.994008         -0.997934   
7            -0.992068         -0.912985         -0.972451         -0.994752   
8            -0.980153         -0.838394         -0.782357         -0.983683   
...                ...               ...               ...               ...   
5874         -0.919666          0.075259         -0.630716         -0.937986   
5875         -0.996596         -0.987491         -0.973345         -0.996372   
5876         -0.994046         -0.940578         -0.917337         -0.994261   
5878         -0.991303         -0.989881         -0.990313         -0.992386   
5880         -0.992662         -0.747190         -0.920248         -0.993410   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
0            -0.962596         -0.965650         -0.929747  ...   
1            -0.993870         -0.987558         -0.937337  ...   
2            -0.982187         -0.995017         -0.942584  ...   
7            -0.943141         -0.976428         -0.925446  ...   
8            -0.816199         -0.743923         -0.914011  ...   
...                ...               ...               ...  ...   
5874          0.176796         -0.613510         -0.866296  ...   
5875         -0.987746         -0.973512         -0.942156  ...   
5876         -0.932830         -0.908088         -0.936219  ...   
5878         -0.988852         -0.991237         -0.936099  ...   
5880         -0.768055         -0.924587         -0.935871  ...   

      fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                           -0.816696                    -0.042494   
1                           -0.693515                    -0.062899   
2                           -0.829311                     0.000265   
7                           -0.704995                    -0.024442   
8                           -0.400197                     0.021212   
...                               ...                          ...   
5874                        -0.091605                    -0.000793   
5875                        -0.956239                     0.122320   
5876                        -0.690363                    -0.034888   
5878                        -0.886851                     0.060173   
5880                        -0.696584                     0.107690   

      angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
0                                -0.044218                          0.307873   
1                                 0.388459                         -0.765014   
2                                -0.525022                         -0.891875   
7                                 0.076332                          0.741277   
8                                -0.009465                         -0.282762   
...                                    ...                               ...   
5874                              0.267189                

In [180]:
# 앞에서 만든 'Activity_dynamic 칼럼 제거
static_beh.drop('Activity_dynamic', axis=1, inplace=True)

# 'Activity'를 'Activity_static' 변수로 변경
static_beh['Activity_static'] = static_beh['Activity'].map({'LAYING': 0, 'SITTING': 1,'STANDING': 2})
static_beh.head()

<ipython-input-180-4582c528010f>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  static_beh.drop('Activity_dynamic', axis=1, inplace=True)
<ipython-input-180-4582c528010f>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  static_beh['Activity_static'] = static_beh['Activity'].map({'LAYING': 0, 'SITTING': 1,'STANDING': 2})


tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288508          -0.009196          -0.103362         -0.988986   
1           0.265757          -0.016576          -0.098163         -0.989551   
2           0.278709          -0.014511          -0.108717         -0.997720   
7           0.272026          -0.001329          -0.125491         -0.992068   
8           0.284338           0.021956          -0.006925         -0.980153   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.962797         -0.967422         -0.989000         -0.962596   
1         -0.994636         -0.987435         -0.990189         -0.993870   
2         -0.981088         -0.994008         -0.997934         -0.982187   
7         -0.912985         -0.972451         -0.994752         -0.943141   
8         -0.838394         -0.782357         -0.983683         -0.816199   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.965650         -0.929747  ...                        -0.816696   
1         -0.987558         -0.937337  ...                        -0.693515   
2         -0.995017         -0.942584  ...                        -0.829311   
7         -0.976428         -0.925446  ...                        -0.704995   
8         -0.743923         -0.914011  ...                        -0.400197   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.042494                             -0.044218   
1                    -0.062899                              0.388459   
2                     0.000265                             -0.525022   
7                    -0.024442                              0.076332   
8                     0.021212                             -0.009465   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                          0.307873                              0.072790   
1                         -0.765014                              0.771524   
2                         -0.891875                              0.021528   
7                          0.741277                              0.729812   
8                         -0.282762                              0.563343   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  Activity  \
0             -0.601120              0.331298              0.165163  STANDING   
1              0.345205             -0.769186             -0.147944    LAYING   
2             -0.833564              0.202434             -0.032755  STANDING   
7             -0.817201              0.037746              0.136129  STANDING   
8             -0.782072              0.242834             -0.025285  STANDING   

   Activity_static  
0                2  
1                0  
2                2  
7                2  
8                2  

[5 rows x 563 columns]

In [181]:
target = ['Activity','Activity_static']
x = static_beh.drop(target, axis=1)
y1 = static_beh['Activity']
y2 = static_beh['Activity_static']

In [182]:
from sklearn.model_selection import train_test_split
x_train, x_val, y2_train, y2_val = train_test_split(x, y2, test_size=0.3, random_state=1)

* Logistic Regression

In [183]:
from sklearn.linear_model import LogisticRegression
model_lr = LogisticRegression()
model_lr.fit(x,y2)

y_pred_lr = model_lr.predict(x_val)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [184]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print('accuracy :',accuracy_score(y2_val, y_pred_lr))
print('='*60)
print(confusion_matrix(y2_val, y_pred_lr))
print('='*60)
print(classification_report(y2_val, y_pred_lr))

accuracy : 0.9866117404737385
[[320   0   0]
 [  0 311   6]
 [  0   7 327]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       320
           1       0.98      0.98      0.98       317
           2       0.98      0.98      0.98       334

    accuracy                           0.99       971
   macro avg       0.99      0.99      0.99       971
weighted avg       0.99      0.99      0.99       971



* Random Forest Classifier

In [185]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier()
model_rf.fit(x, y2)

y_pred_rf = model_rf.predict(x_val)

In [186]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print('accuracy :',accuracy_score(y2_val, y_pred_lr))
print('='*60)
print(confusion_matrix(y2_val, y_pred_lr))
print('='*60)
print(classification_report(y2_val, y_pred_lr))

accuracy : 0.9866117404737385
[[320   0   0]
 [  0 311   6]
 [  0   7 327]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       320
           1       0.98      0.98      0.98       317
           2       0.98      0.98      0.98       334

    accuracy                           0.99       971
   macro avg       0.99      0.99      0.99       971
weighted avg       0.99      0.99      0.99       971



### (3) 단계2-2 : 동적 동작 세부 분류

* 세부 요구사항
    * 동적 행동(Walking, Walking Upstairs, Walking Downstairs)인 데이터 추출
    * Walking, Walking Upstairs, Walking Downstairs 를 분류하는 모델을 생성
    * 몇가지 모델을 만들고 가장 성능이 좋은 모델을 선정하시오.

In [187]:
data['Activity'].unique()

array(['STANDING', 'LAYING', 'WALKING', 'WALKING_DOWNSTAIRS',
       'WALKING_UPSTAIRS', 'SITTING'], dtype=object)

In [188]:
# 동적 행동(Laying, Sitting, Standing)에 해당하는 데이터 추출
static_act = data.loc[(data['Activity'] == 'WALKING')|(data['Activity'] == 'WALKING_UPSTAIRS')|(data['Activity'] == 'WALKING_DOWNSTAIRS')]

# 추출된 데이터 확인
display(static_act)

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
3              0.289795          -0.035536          -0.150354   
4              0.394807           0.034098           0.091229   
5              0.330708           0.007561          -0.061371   
6              0.121465          -0.031902          -0.005196   
12             0.303885           0.002768          -0.038613   
...                 ...                ...                ...   
5868           0.277709          -0.053919          -0.098746   
5869           0.252496          -0.009773          -0.118293   
5873           0.264961          -0.034719          -0.088140   
5877           0.191568           0.013328          -0.105174   
5879           0.212787          -0.048130          -0.121001   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
3            -0.231727         -0.006412         -0.338117         -0.273557   
4             0.088489         -0.106636         -0.388502         -0.010469   
5            -0.215760          0.101075          0.072949         -0.269857   
6            -0.152198         -0.113104         -0.239423         -0.202401   
12           -0.168656          0.190336         -0.140473         -0.205134   
...                ...               ...               ...               ...   
5868         -0.589970         -0.076626         -0.500837         -0.605474   
5869         -0.155168         -0.244513         -0.044524         -0.244367   
5873         -0.368158         -0.074514         -0.229606         -0.394387   
5877         -0.126969         -0.121729         -0.327480         -0.192523   
5879         -0.041373          0.052449         -0.585361         -0.100714   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
3             0.014245         -0.347916          0.008288  ...   
4            -0.109680         -0.346372          0.584131  ...   
5             0.060060          0.101298         -0.019263  ...   
6            -0.164698         -0.247099          0.114668  ...   
12            0.101144         -0.120572         -0.000818  ...   
...                ...               ...               ...  ...   
5868         -0.142798         -0.506696         -0.533485  ...   
5869         -0.229509         -0.042199          0.291682  ...   
5873         -0.082437         -0.243525         -0.261087  ...   
5877         -0.109923         -0.295286          0.078644  ...   
5879          0.023353         -0.554707          0.219814  ...   

      fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
3                           -0.408956                    -0.255125   
4                           -0.563437                    -0.044344   
5                           -0.887024                    -0.030645   
6                           -0.775779                     0.445206   
12                          -0.329728                    -0.040030   
...                               ...                          ...   
5868                        -0.268237                    -0.076922   
5869                        -0.752980                     0.619246   
5873                        -0.046157                     0.037517   
5877                        -0.879215                     0.721718   
5879                        -0.053556                     0.260880   

      angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
3                                 0.612804                          0.747381   
4                                -0.845268                         -0.974650   
5                                -0.852091                         -0.500195   
6                                -0.003487                         -0.940185   
12                                0.257252                          0.076091   
...                                    ...                               ...   
5868                              0.706620                

In [189]:
# 앞에서 만든 'Activity_dynamic 칼럼 제거
static_act.drop('Activity_dynamic', axis=1, inplace=True)

# 'Activity'를 'Activity_act' 변수로 변경
static_act['Activity_act'] = static_act['Activity'].map({'WALKING': 3, 'WALKING_UPSTAIRS': 4,'WALKING_DOWNSTAIRS': 5})
static_act.head()

<ipython-input-189-129fa79e0f4b>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  static_act.drop('Activity_dynamic', axis=1, inplace=True)
<ipython-input-189-129fa79e0f4b>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  static_act['Activity_act'] = static_act['Activity'].map({'WALKING': 3, 'WALKING_UPSTAIRS': 4,'WALKING_DOWNSTAIRS': 5})


tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
3            0.289795          -0.035536          -0.150354         -0.231727   
4            0.394807           0.034098           0.091229          0.088489   
5            0.330708           0.007561          -0.061371         -0.215760   
6            0.121465          -0.031902          -0.005196         -0.152198   
12           0.303885           0.002768          -0.038613         -0.168656   

    tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
3          -0.006412         -0.338117         -0.273557          0.014245   
4          -0.106636         -0.388502         -0.010469         -0.109680   
5           0.101075          0.072949         -0.269857          0.060060   
6          -0.113104         -0.239423         -0.202401         -0.164698   
12          0.190336         -0.140473         -0.205134          0.101144   

    tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
3          -0.347916          0.008288  ...                        -0.408956   
4          -0.346372          0.584131  ...                        -0.563437   
5           0.101298         -0.019263  ...                        -0.887024   
6          -0.247099          0.114668  ...                        -0.775779   
12         -0.120572         -0.000818  ...                        -0.329728   

    angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
3                     -0.255125                              0.612804   
4                     -0.044344                             -0.845268   
5                     -0.030645                             -0.852091   
6                      0.445206                             -0.003487   
12                    -0.040030                              0.257252   

    angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
3                           0.747381                             -0.072944   
4                          -0.974650                             -0.887846   
5                          -0.500195                              0.306091   
6                          -0.940185                              0.041387   
12                          0.076091                             -0.123425   

    angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  \
3              -0.695819              0.287154              0.111388   
4              -0.705029              0.264952              0.137758   
5              -0.552729              0.253885              0.291256   
6              -0.886603              0.173338             -0.005627   
12             -0.752882              0.266729              0.045692   

              Activity  Activity_act  
3              WALKING             3  
4   WALKING_DOWNSTAIRS             5  
5     WALKING_UPSTAIRS             4  
6              WALKING             3  
12             WALKING             3  

[5 rows x 563 columns]

In [190]:
target = ['Activity','Activity_act']
x = static_act.drop(target, axis=1)
y1 = static_act['Activity']
y2 = static_act['Activity_act']

In [191]:
from sklearn.model_selection import train_test_split
x_train, x_val, y2_train, y2_val = train_test_split(x, y2, test_size=0.3, random_state=1)

* Logistic Regression

In [192]:
from sklearn.linear_model import LogisticRegression
model_lr = LogisticRegression()
model_lr.fit(x,y2)

y_pred_lr = model_lr.predict(x_val)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [193]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print('accuracy :',accuracy_score(y2_val, y_pred_lr))
print('='*60)
print(confusion_matrix(y2_val, y_pred_lr))
print('='*60)
print(classification_report(y2_val, y_pred_lr))

accuracy : 1.0
[[307   0   0]
 [  0 245   0]
 [  0   0 243]]
              precision    recall  f1-score   support

           3       1.00      1.00      1.00       307
           4       1.00      1.00      1.00       245
           5       1.00      1.00      1.00       243

    accuracy                           1.00       795
   macro avg       1.00      1.00      1.00       795
weighted avg       1.00      1.00      1.00       795



* Random Forest Classifier

In [194]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier()
model_rf.fit(x, y2)

y_pred_rf = model_rf.predict(x_val)

In [195]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print('accuracy :',accuracy_score(y2_val, y_pred_lr))
print('='*60)
print(confusion_matrix(y2_val, y_pred_lr))
print('='*60)
print(classification_report(y2_val, y_pred_lr))

accuracy : 1.0
[[307   0   0]
 [  0 245   0]
 [  0   0 243]]
              precision    recall  f1-score   support

           3       1.00      1.00      1.00       307
           4       1.00      1.00      1.00       245
           5       1.00      1.00      1.00       243

    accuracy                           1.00       795
   macro avg       1.00      1.00      1.00       795
weighted avg       1.00      1.00      1.00       795



### (4) 분류 모델 합치기


* 세부 요구사항
    * 두 단계 모델을 통합하고, 새로운 데이터(test)에 대해서 최종 예측결과와 성능평가가 나오도록 함수로 만들기
    * 데이터 파이프라인 구축 : test데이터가 로딩되어 전처리 과정을 거치고, 예측 및 성능 평가 수행

![](https://github.com/DA4BAM/image/blob/main/pipeline%20function.png?raw=true)

In [196]:
test.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.284379          -0.021981          -0.116683         -0.992490   
1           0.277440          -0.028086          -0.118412         -0.996620   
2           0.305833          -0.041023          -0.087303          0.006880   
3           0.276053          -0.016487          -0.108381         -0.995379   
4           0.271998           0.016904          -0.078856         -0.973468   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.979640         -0.963321         -0.992563         -0.977304   
1         -0.927676         -0.972294         -0.997346         -0.931405   
2          0.182800         -0.237984          0.005642          0.028616   
3         -0.983978         -0.975854         -0.995877         -0.985280   
4         -0.702462         -0.869450         -0.979810         -0.711601   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-skewness()  \
0         -0.958142         -0.938850  ...                        -0.509523   
1         -0.971788         -0.939837  ...                        -0.210792   
2         -0.236474          0.016311  ...                         0.579587   
3         -0.974907         -0.941425  ...                        -0.566291   
4         -0.856807         -0.920760  ...                         0.447577   

   fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                        -0.850065                    -0.018043   
1                        -0.613367                    -0.022456   
2                         0.394388                    -0.362616   
3                        -0.841455                     0.289548   
4                         0.214219                     0.010111   

   angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
0                              0.092304                          0.074220   
1                             -0.155414                          0.247498   
2                              0.171069                          0.576349   
3                              0.079801                         -0.020033   
4                              0.114179                         -0.830776   

   angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
0                             -0.714534             -0.671943   
1                             -0.112257             -0.826816   
2                             -0.688314             -0.743234   
3                              0.291898             -0.639435   
4                             -0.325098             -0.840817   

   angle(Y,gravityMean)  angle(Z,gravityMean)  Activity  
0             -0.018351             -0.185733   SITTING  
1              0.184489             -0.068699  STANDING  
2              0.272186              0.053101   WALKING  
3             -0.111998             -0.123298   SITTING  
4              0.116237             -0.096615  STANDING  

[5 rows x 562 columns]

In [198]:
def model_pipline(data):
    # 동적 구분 칼럼 추가
    data['Activity_dynamic'] = data['Activity'].replace({'STANDING': 0,
                                                         'SITTING': 0,
                                                         'LAYING': 0,
                                                         'WALKING': 1,
                                                         'WALKING_UPSTAIRS': 1,
                                                         'WALKING_DOWNSTAIRS': 1})
    x = data.drop(['Activity', 'Activity_dynamic'], axis=1)
    y1 = data['Activity']
    y2 = data['Activity_dynamic']

    model1 = RandomForestClassifier(random_state=1)
    model1.fit(x, y2)

    y_pred_rf = model1.predict(x)
    data['predict'] = y_pred_rf

    df_stop = data[data['predict'] == 0]
    x_stop = df_stop.drop(['Activity', 'Activity_dynamic'], axis=1)
    y_stop = df_stop['Activity']

    df_act = data[data['predict'] == 1]
    x_act = df_act.drop(['Activity', 'Activity_dynamic'], axis=1)
    y_act = df_act['Activity']

    x_train, x_val, y_train, y_val = train_test_split(x_stop, y_stop, test_size=0.3, random_state=1)
    x_train2, x_val2, y_train2, y_val2 = train_test_split(x_act, y_act, test_size=0.3, random_state=1)

    model2_0 = RandomForestClassifier(random_state=1)
    model2_0.fit(x_train, y_train)
    y_pred_rf2_0 = model2_0.predict(x_val)

    print('정적 동작 예측모델 평가')
    print(classification_report(y_val, y_pred_rf2_0))

    model2_1 = RandomForestClassifier(random_state=1)
    model2_1.fit(x_train2, y_train2)
    y_pred_rf2_1 = model2_1.predict(x_val2)

    print('동적 동작 예측모델 평가')
    print(classification_report(y_val2, y_pred_rf2_1))

#### 1) 함수 만들어서 분류모델 합치기

In [199]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

def train_static_dynamic_model(data):
    data['Activity_dynamic'] = data['Activity'].replace({'STANDING': 0,
                                                         'SITTING': 0,
                                                         'LAYING': 0,
                                                         'WALKING': 1,
                                                         'WALKING_UPSTAIRS': 1,
                                                         'WALKING_DOWNSTAIRS': 1})

    x = data.drop(['Activity', 'Activity_dynamic'], axis=1)
    y1 = data['Activity']
    y2 = data['Activity_dynamic']

    # 데이터 분할
    x_train, x_val, y2_train, y2_val = train_test_split(x, y2, test_size=0.3, random_state=1)

    # 로지스틱 회귀 모델 학습
    model_lr = LogisticRegression()
    model_lr.fit(x_train, y2_train)

    return model_lr

def train_static_model(data):
    static_beh = data.loc[(data['Activity'] == 'LAYING') | (data['Activity'] == 'SITTING') | (data['Activity'] == 'STANDING')]
    static_beh.drop('Activity_dynamic', axis=1, inplace=True)
    static_beh['Activity_static'] = static_beh['Activity'].map({'LAYING': 0, 'SITTING': 1, 'STANDING': 2})

    x = static_beh.drop(['Activity', 'Activity_static'], axis=1)
    y2 = static_beh['Activity_static']

    x_train, x_val, y2_train, y2_val = train_test_split(x, y2, test_size=0.3, random_state=1)

    model_lr = LogisticRegression()
    model_lr.fit(x_train, y2_train)

    y_pred_lr1 = model_lr.predict(x_val)

    print('정적 동작 예측모델 평가')
    print(classification_report(y2_val, y_pred_lr1))

    return model_lr, classification_report(y2_val, y_pred_lr1)

def train_dynamic_model(data):
    static_act = data.loc[(data['Activity'] == 'WALKING') | (data['Activity'] == 'WALKING_UPSTAIRS') | (data['Activity'] == 'WALKING_DOWNSTAIRS')]
    static_act.drop('Activity_dynamic', axis=1, inplace=True)
    static_act['Activity_act'] = static_act['Activity'].map({'WALKING': 3, 'WALKING_UPSTAIRS': 4, 'WALKING_DOWNSTAIRS': 5})

    x = static_act.drop(['Activity', 'Activity_act'], axis=1)
    y2 = static_act['Activity_act']

    x_train, x_val, y2_train, y2_val = train_test_split(x, y2, test_size=0.3, random_state=1)

    model_lr = LogisticRegression()
    model_lr.fit(x_train, y2_train)

    y_pred_lr2 = model_lr.predict(x_val)

    print('동적 동작 예측모델 평가')
    print(classification_report(y2_val, y_pred_lr2))

    return model_lr, classification_report(y2_val, y_pred_lr2)

#### 2) test 셋으로 예측하고 평가하기

In [200]:
model_static_dynamic, model_static, model_dynamic = merge_models(test)

<ipython-input-199-21f2b9e3ecb7>:28: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  static_beh.drop('Activity_dynamic', axis=1, inplace=True)
<ipython-input-199-21f2b9e3ecb7>:29: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  static_beh['Activity_static'] = static_beh['Activity'].map({'LAYING': 0, 'SITTING': 1, 'STANDING': 2})
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the da

정적 동작 예측모델 평가
              precision    recall  f1-score   support

           0       0.99      1.00      0.99        82
           1       0.94      0.91      0.92        79
           2       0.93      0.94      0.94        89

    accuracy                           0.95       250
   macro avg       0.95      0.95      0.95       250
weighted avg       0.95      0.95      0.95       250

동적 동작 예측모델 평가
              precision    recall  f1-score   support

           3       0.99      0.99      0.99        69
           4       0.98      0.98      0.98        62
           5       1.00      1.00      1.00        61

    accuracy                           0.99       192
   macro avg       0.99      0.99      0.99       192
weighted avg       0.99      0.99      0.99       192



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
